### ISSUE TITLE
[BUG] Some players don't contribute to formation ratings.

### ISSUE THREAD

**Issue by Cold-Burn** [ho-dev/HattrickOrganizer#1117]
**Describe the bug**
Some players don't contribute to formation ratings.

Somehow the player has something that prevents HO to consider its contribution.
In the past 1.437 was only affecting one player but randomly. 
Then I updated to 2.1, it fixed to one specific player for a while, on the past week the issue become to happen to two players. 
I have updated to the HO-4.1.3310.2-portable-win-JRE, same behaviour, then after subskill calculation came back to the behaviour of 2.1, fixed again to one specific player.

I've checked previous issues to see if this was something already reported.

I'm not sure if its HO bug or if the database is becoming corrupt. Anyway there should be a way to validate data and correct issues with the database.

Please inform what information do you need to analyze better this issue.

**Platform information:**
 - OS: [Windows 10]
 - Version (1607)

Thank you.

**Comment by wsbrenk** [comment]
@Cold-Burn: Could you please check if there are suspicuous entries in your log file  in folder %APPDATA%/HO/logs

**Comment by Cold-Burn** [comment]
> 
> 
> @Cold-Burn: Could you please check if there are suspicuous entries in your log file in folder %APPDATA%/HO/logs

I'm not sure what to search for so please check the following:
[HO-2021-08-14.log](https://github.com/akasolace/HO/files/6987930/HO-2021-08-14.log)

![imagem](https://user-images.githubusercontent.com/88949554/129475127-958410af-d8c5-44c5-8261-aee0eb61ea6e.png)

The player that usually fails to contribute to formation ratings is Áskell Halldórsson (445327399).

**Comment by wsbrenk** [comment]
Although there are errors included, these are no real errors ;-(

**Comment by Cold-Burn** [comment]
> 
> 
> Although there are errors included, these are no real errors ;-(

Surely there is an error somewhere.
What files do you need? error.log or output.log?

I made more tests on lineup calculation please check below what happens:
baseline
![imagem](https://user-images.githubusercontent.com/88949554/129479091-0db4ade5-8315-4299-ab3b-b5425c40755c.png)

Changing Áskell to Huertas - result Áskell is contributing
![imagem](https://user-images.githubusercontent.com/88949554/129479143-01fbc390-a496-449e-82fd-31a3e562581e.png)

Now change on baseline on Gassamene to Leão/Kechev - decrease in results when Áskell is on formation
![imagem](https://user-images.githubusercontent.com/88949554/129479176-ae080624-ae22-459c-95e9-7f5a0aa3c2ea.png)
![imagem](https://user-images.githubusercontent.com/88949554/129479228-007e0986-a97b-4147-8601-78511ed9270d.png)

Changing Áskell to Huertas - result Áskell isn't contributing
![imagem](https://user-images.githubusercontent.com/88949554/129479213-4b581e61-fe62-4be7-862e-71c545f440ec.png)
![imagem](https://user-images.githubusercontent.com/88949554/129479245-23fb7736-a3cc-4518-9ab1-b9568410f62c.png)

**Comment by wsbrenk** [comment]
I didn't want to contradict you. The errors in the log are not real errors.

**Comment by akasolace** [comment]
@Cold-Burn  @wsbrenk I do not understand the issue here,  what exactly make you think that one player is not contributing ?

**Comment by wsbrenk** [comment]
we have got this one #992

**Comment by wsbrenk** [comment]
since the rating panel is completly redesigned, i don't know if this issue still exists?

**Comment by wsbrenk** [comment]
@Cold-Burn could you investigate if the bug still exists in the current version (https://github.com/akasolace/HO/releases/tag/dev)? Since it is developer version please don't use it without backups of your database and program directories of your current HO installation.

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/131252540-10061c84-7ffa-4b53-bd41-c8bf2f742e36.png)

![image](https://user-images.githubusercontent.com/11821502/131252534-84462b15-235e-4cb6-9849-848185d9d93a.png)

Suspicious:
left central midfielder has negative impact on ratings of the right side. right central midfielder on the opposite side.

**Comment by Cold-Burn** [comment]
Last formation calculated Áskell has contributed to formation ratings. HO-4.1.3310.2-portable-win-JRE
I will keep an eye out because from my previous findings, behaviour seems to depend on other players in formation.

Regarding your pictures its very strange your findings. 
Even considering that you go from a "invalid" formation 5-3-1 to a "valid" formation 5-4-1.

**Comment by wsbrenk** [comment]
@Cold-Burn maybe this is an effect of overcrowding - but i'm really not sure!

**Comment by akasolace** [comment]
from lineup simulation in HT,

default lineup:

![image](https://user-images.githubusercontent.com/1136496/131261179-1f4cdeea-36ec-49c1-9470-dd74511a738a.png)


adding a cd player weaker than other defender has negative impact because of overcrowding 

![image](https://user-images.githubusercontent.com/1136496/131261190-95711b1a-e5a5-4222-978f-cfe3f9843b1d.png)

**Comment by Cold-Burn** [comment]
This effect on formation still happens in HO-5.0.3843.2-portable-win-JRE.
Normally occurs with player Áskell Halldórsson but not everytime.

**Comment by Cold-Burn** [comment]
Please see below. I don't know how to make it more evident that something is wrong.

![imagem](https://user-images.githubusercontent.com/88949554/152646365-763b7141-21dc-4e13-ba67-4910171d7ef0.png)
![imagem](https://user-images.githubusercontent.com/88949554/152646382-c6c3e046-1df1-4585-8682-89fcf4a6ba73.png)

**Comment by wsbrenk** [comment]
@Cold-Burn very strange - do you want to upload your database - then i could try to debug this

**Comment by wsbrenk** [comment]
renamed my best playmaker to Áskell Halldórsson, but i couldn't reproduce the error.

**Comment by Cold-Burn** [comment]
Hello @wsbrenk 
Today I've updated and Áskell Halldórsson didn't contribute to formation as expected.
After I've sent tactics for the game.
Later in the day I've updated HO again and Áskell Halldórsson now contribute to formation.

So I think that its something related to the update and if player is on game formation.
I will inform you if it always happens like this in the future.

**Comment by Cold-Burn** [comment]
Hello @wsbrenk 
I will keep analyzing but when I update HO and have Áskell Halldórsson on formation in hattrick all is ok in HO.
If sent formation or preset formation don't have Áskell Halldórsson he doesn't contribute to lineup ratings when HO is updated.

**Comment by Cold-Burn** [comment]
Hello @wsbrenk 
I confirm you that my previous post is what's happening.

Now everytime that I update HO, I go previously to formation and send Áskell Halldórsson on formation in advance this allows me to bypass this strange bug.

**Comment by Cold-Burn** [comment]
I believe that you can emulate this behaviour by naming your player and following the same update/formation procedure.

**Comment by wsbrenk** [comment]
@Cold-Burn a renamed player will be replaced with correct name if i update/download ho data.

if you like you could send me your database again - so i could try to reproduce the steps you describe.

**Comment by wsbrenk** [comment]
@Cold-Burn since the download and storing of lineups changed in HO6 version, you could try to check if this will fix your bug. But please don't use the dev version without backup of your current HO installation including your databases.

**Comment by wsbrenk** [comment]
Rating prediciton is replaced by schum's rating formula in HO8
