### ISSUE TITLE
[FEATURE] Allow users to edit colors ....

### ISSUE THREAD

**Issue by wsbrenk** [ho-dev/HattrickOrganizer#1242]
Feedback from peppermill at HT forum:

Squad:
Can you take another color here for dark green, green and blue is hard to distinguish 

![image](https://user-images.githubusercontent.com/11821502/137686230-e58c5e39-0a2d-4ecc-b469-5c919902f87d.png)

**Comment by akasolace** [comment]
@wsbrenk I renamed this one cause I think we can do a more general feature ... what do you think ?

**Comment by wsbrenk** [comment]
![image](https://github.com/ho-dev/HattrickOrganizer/assets/11821502/7ac75756-80e0-4b44-b06e-b0a26c40a138)

**Comment by wsbrenk** [comment]
Now i will add a color picker

**Comment by tychobrailleur** [comment]
Nice :)

**Comment by wsbrenk** [comment]
The following actions i plan to implement:

* editing the color reference column will show a combo box with all color names
* selecting a new color reference will change the color value accordingly (the referenced color will be displayed and the color value editing will be disabled)
* if no color reference is selected editing the color value cell should invoke a color picker to set a new color  value
* the user settings will be stored in the new color database table which override the standard settings on HO startup

Currently I'm struggling with the empty combo box entry in color reference combo box, which is a very slim entry which is not easily selectable...

**Comment by wsbrenk** [comment]
Now it is ready for review

TODOs (new ticket candidate): There were 200 color names defined in HO. Some of them are removed by this merge request. It would be useful to remove more of them and name them more uniquely to make editing of colors more easier.
