### ISSUE TITLE
[BUG] checkbox Old League Data functionality

### ISSUE THREAD

**Issue by masterpatje** [ho-dev/HattrickOrganizer#1434]
**Describe the bug**
The checkbox Old League Data does not do anything by itself other then making the selecting menu available, but when no seasons are selected it doesn't download anything. Best would be to download all seasons by checking the box, because this is a one time use function to get history data. And if people don't want all data, they can just refer to the method of selecting a single season.

I seperated this bug from #1413 for clarity purposes. @wsbrenk I am unsure if you already created a notification for yourself for this bug/feature?

**To Reproduce**
1. Download data
2. Deselect "Download filter"
3. Select "Old League Data"
4. Do not select any seasons.
5. In that case the checkbox doesn't do anything.

**Screenshots**
![image](https://user-images.githubusercontent.com/102049050/161700232-86985705-cde4-45c5-85a2-95f41109e217.png)

**Platform information:**
 - OS: Windows 10
 - Version 261

**Additional context**
Possible solutions:
**Best**: If the checkbox is checked _without_ selecting any seasons, all seasons are included
**Alternative**: If the checkbox is checked then automatically the first seasons is high-lighted as included to be included in the download (however I would strongly prefer that all seasons are included, because this feature is only used once normally)

**Comment by masterpatje** [comment]
Additional idea is if you download all seasons by only using the checkbox, that all "actual seasons" will be automatically downloaded, so that you don't have to click through the pop-up windows.

**Comment by wsbrenk** [comment]
![image](https://github.com/ho-dev/HattrickOrganizer/assets/11821502/248f3838-0857-494d-a76b-c184c78df87d)

i put the previous series data download to the left check box tree. Now i'm looking for a nice indication of partial checked nodes (not all children are checked). I don't like the available TristateCheckbox that much.

**Comment by wsbrenk** [comment]
found this: 

![image](https://github.com/ho-dev/HattrickOrganizer/assets/11821502/34233ff2-2b39-4cd9-8d61-4d8a997acc6c)
