### ISSUE TITLE
[FEATURE] Subskill recalculation textual information

### ISSUE THREAD

**Issue by masterpatje** [ho-dev/HattrickOrganizer#1556]
v6.0.327

Added information. Textual description of what is actually being taken into consideration for recalculation. From my textual example you can extract a generic code. The date alone is less usefull for determining which training weeks are taken into consideration.

![image](https://user-images.githubusercontent.com/102049050/176947007-88c562f1-5d95-4d49-ab94-048092ccb898.png)

**Title:** Subskill recalculation (7 **training** weeks)

"Subskill recalculation for the last 7 **training** weeks (since 5/13/22). 
**First training week included is Season 70 Week 7. Last training week included is Season 70 Week 13.**
Start recalculation?"

**Comment by wsbrenk** [comment]
![image](https://github.com/ho-dev/HattrickOrganizer/assets/11821502/6fa4e654-d895-4e46-8848-e6c25219ba3e)
