### ISSUE TITLE
[FEATURE] Window adjusting youth tab on initial installation and adjusting width of the sliders

### ISSUE THREAD

**Issue by masterpatje** [ho-dev/HattrickOrganizer#1558]
**v6.0.327**

On initial installation the youth tab -> player looks likes this:
![image](https://user-images.githubusercontent.com/102049050/176953992-170f81e7-7133-4919-961e-b5414d39b0df.png)

I would prefer to have the initial window view be something like this:
Also width of the sliders could be made smaller so that the graph to the right is shown.
![image](https://user-images.githubusercontent.com/102049050/176954086-7b0671de-78f9-4850-9e74-fca30bdf92a8.png)

Youth tab -> Training tab:
![image](https://user-images.githubusercontent.com/102049050/176954177-aa6b5243-bc4d-445c-be4f-78c7c18c7cb0.png)

I would prefer to have the initial window view be something like this:
p.s. is it correct that primary and secondary training are set to unknown?
![image](https://user-images.githubusercontent.com/102049050/176954258-60d1efd2-5393-4186-9f13-1bf3043395cb.png)

**Comment by vomme2020** [comment]
@wsbrenk 
Adding to this - hope that is OK
Would it be possible to put the graph in a separate "area", so you can re-size the split between sliders and graph?
Kind of what is done on the Lineup tab.

**Comment by wsbrenk** [comment]
@vomme2020 this is done with #1990
