### ISSUE TITLE
[BUG] Matches - Several Features | Clean Up Ladder Competition Matches |

### ISSUE THREAD

**Issue by masterpatje** [ho-dev/HattrickOrganizer#1587]
**Describe the bug**

**To Reproduce**
1. Go to 'Matches'

**Screenshots**
**Screenshot 1: selection filter is the same**
![image](https://user-images.githubusercontent.com/102049050/179726133-0673d6aa-89fa-4e33-9208-e825a1008c75.png)

**Screenshot 2: "ladder competition" matches** (exclude option)
- I wish to have the option to exclude "ladder competition" matches from the selection of matches
- In general I would like to select the type of matches to be included, for example select all cup matches **and** all league matches. Now I can only select on or the other.
![image](https://user-images.githubusercontent.com/102049050/179725702-9eff582d-dd5c-49a4-91e6-d9aecea186c2.png)

**Platform information:**
 - OS: Windows 10
 - Version 7.0.350

**Additional context**
**Additional problem: Ladder competition matches are not deleted on clean up:**

![image](https://user-images.githubusercontent.com/102049050/179727272-319db967-8cd5-4ce7-a5d0-3321472b218f.png)

![image](https://user-images.githubusercontent.com/102049050/179727376-57833dce-276c-4b8d-92d1-2aec285bdd66.png)

**Result: No ladder competition matches are deleted.**
 [Debug]   DBCleanupTool: Removing old matches: removeDateOwnMatches=null, removeDateOwnFriendlies=null, removeDateOtherMatches=2022-07-19 12:03:34.797, removeDateOtherFriendlies=2022-07-19 12:03:34.797
 [Debug]   DBCleanupTool: Removed 0/42 matches from DB!
![image](https://user-images.githubusercontent.com/102049050/179727447-7fffe642-dc37-4e3a-834a-8fd0a07ae120.png)

**Comment by wsbrenk** [comment]
screenshot 1: the tagged entries are not identical. the first one should show your cup and qualification matches too.

**Comment by wsbrenk** [comment]
screenshot 2: show my competition matches should deliver approximately the desired. (league + cup + qualification)

**Comment by wsbrenk** [comment]
@masterpatje i'm with you, that selection by combobox items is not the best choice. i would suggest to improve this in HO7. maybe we could do it with check boxes.

**Comment by wsbrenk** [comment]
concerning cleanup: "Other matches" seems to be misleading. it does mean matches of other teams, not other match types.

**Comment by wsbrenk** [comment]
improvements of db cleanup should also be part of HO7 development.

**Comment by masterpatje** [comment]
Fine with me to tackle the features in 7.0. And your comments where clear.

**Comment by tychobrailleur** [comment]
I started some work on this, in particular in the Matches tab.  For the DB cleanup tool, I have clarified the labels, and I am also planning on adding matches count (right now not super pretty, but I will improve layout):
![Screenshot from 2023-05-15 19-50-42](https://github.com/akasolace/HO/assets/114285/2359599f-bd0b-4dfc-aad4-0dfd29db19a2)

One thing I observed, which I didn't expect is that when deleting other people's matches, this affected some of my own players ratings:

![Peek 2023-05-15 20-05](https://github.com/akasolace/HO/assets/114285/4a3689dd-c297-4c86-aae3-cc61f4dbedfd)

This doesn't quite make sense to me, what do you think, @wsbrenk?

**Comment by wsbrenk** [comment]
@tychobrailleur absolute agreement - this should not happen. but i can't reproduce it for now.

**Comment by tychobrailleur** [comment]
> One thing I observed, which I didn't expect is that when deleting other people's matches, this affected some of my own players ratings:

That's the last thing to solve.  This can be reproduced by starting HO, and selected the first element in the list of HRF files.  I am looking into this.
