### ISSUE TITLE
Cannot install "HOSetup-6.0.368.2-JRE".

### ISSUE THREAD

**Issue by fjrn200** [ho-dev/HattrickOrganizer#1625]
When I try to install, the system shows the following message:
Could not load main class.
Log: C:\Users\User\AppData\Local\Temp\i4j_nlog_01.log

The times I try to install again, the file numbering increases, ...._02.log, ....03.log, ....04.log, ...

I always used the HO. I don't know what I'm doing wrong.
Thank you for your help.

**Additional information**
I use Windows 11

**Comment by wsbrenk** [comment]
@fjrn200 could you please upload the log file (just drag the file to this thread)

**Comment by fjrn200** [comment]
Follow as per your request.
Thank you very much

[i4j_nlog_1.log](https://github.com/akasolace/HO/files/9338201/i4j_nlog_1.log)

**Comment by fjrn200** [comment]
I uninstaller Java and reinstalled it again, but the problem continued.
Did the file I sent help to find the problem?
I need help.
Thank you very much

**Comment by masterpatje** [comment]
While you await wsbrenk his answer. You can try the following; https://github.com/akasolace/HO/releases/download/6.0/HO-6.0.368.2-portable-win-JRE.zip

It is a portable version. You need 7-zip (freeware) to unpack the content. 

You can see if the problem also exist with that version. Best of luck.

**Comment by fjrn200** [comment]
Greetings

I did the zip file extraction, but unfortunately the problem remains.

I'm using version (build 1.8.0_34-b10) of Java, is this version correct for
HO ?

Thanks for your help.

Em sáb., 20 de ago. de 2022 às 04:09, masterpatje ***@***.***>
escreveu:

**Comment by wsbrenk** [comment]
~~~
[3:937] JVM created
[3:952] ERROR: did not find NativeLogger class
[3:968] load helper dll
[3:968] helper dll (in-module) 00007FF74EE30000
[3:968] ERROR: did not find com/install4j/runtime/installer/platform/win32/Common
[3:984] ERROR: did not find WinDel class
[3:984] setting exe4j.moduleName to D:\Users\fjrn\Downloads\HOSetup-7.0.370.0-DEV-JRE.exe
[3:984] main class: com/install4j/runtime/launcher/WinLauncher
[3:999] ERROR: could not find main class
~~~

i have only one idea: is your antivirus deleting files during your installation?

**Comment by fjrn200** [comment]
I use the default Microsof Defender antivirus on Windows 11.

When I try to install the program and the error occurs, it does not show any indication or message on the screen informing that the system is blocking or deleting some file.

I put the message "Couldn't load main class" on Google and it showed articles talking about renaming a file or not finding a file. Some Java process that I have no knowledge to analyze.

If you need any other information, I'm always available.

Thanks again for your help.

**Comment by wsbrenk** [comment]
does this error still exist or could you successfully retry with a new correctly downloaded ho installer?

**Comment by fjrn200** [comment]
OK, obrigado.

Com um novo instalador está OK.

Obrigado
