### ISSUE TITLE
[BUG] Database update failed

### ISSUE THREAD

**Issue by Buerstl** [ho-dev/HattrickOrganizer#1636]
**Describe the bug**

**To Reproduce**

**Screenshots**
![Screenshot 2022-09-18 121224](https://user-images.githubusercontent.com/113830223/190897114-fa1ceef9-86ed-448d-b6c9-1b0f2ca3a287.png)

**Platform information:**
 - OS: Windows 
 - Version (including build number)

**Additional context**

**Comment by Buerstl** [comment]
[db_singleUser-2022-9-18.zip](https://github.com/akasolace/HO/files/9593745/db_singleUser-2022-9-18.zip)

**Comment by wsbrenk** [comment]
hsqldb.original_version=1.8.0

this looks like a real old db version which is not supported by HO6 anymore. are you sure, that it was the correct database folder, where you found the backup?

**Comment by Buerstl** [comment]
Hallo Brenk,

 

es gibt nur diese Datenbank und bei jedem Versuch neu zu starten wird ein neues zip erzeugt. Sollte ich eine ältere Version von HO installieren um dann die alte Datenbank wieder benützen zu können?

 

Gesendet: Sonntag, 18. September 2022 um 16:59 Uhr
Von: "wsbrenk" ***@***.***>
An: "akasolace/HO" ***@***.***>
Cc: "Buerstl" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [akasolace/HO] [BUG] (Issue #1636)


 

hsqldb.original_version=1.8.0

this looks like a real old db version which is not supported by HO6 anymore. are you sure, that it was the correct database folder, where you found the backup?

**Comment by wsbrenk** [comment]
If this database is from HO versions before 3.0 you have to install HO3 to upgrade your database to a supported level of the new HO versions.
