### ISSUE TITLE
[FEATURE] Move repository to https://github.com/ho-dev

### ISSUE THREAD

**Issue by wsbrenk** [ho-dev/HattrickOrganizer#1736]
Todo:
 
- [x] extend ownership of HO-Dev to @tychobrailleur and me (@wsbrenk )
- [x] move the HO repository to https://github.com/ho-dev
- [x] update security tokens (build.gradle, ...)
- [x] repair github integration of poeditor-
- [x] update of new HO versions use the new repository (links in HO sources)
- [x] update old repository to update to versions of the new repository (needed by HO versions <=7)
- [x] publish new repository url to HO users
- [x] migrate issues to new repo
- [x] Add permissions to existing developers
- [x] Update current repo to mark it as deprecated, and link to new one
- [x] Update Url in https://www84.hattrick.org/Community/CHPP/ChppProgram.aspx?ApplicationId=3330
- [x] Update https://www84.hattrick.org/Community/CHPP/ChppProgramDetails.aspx?ApplicationId=3330

what is missing?

**Comment by tychobrailleur** [comment]
There are other things like:

- Do you want to migrate issues to new repo
- Add permissions to existing developers
- Update links to new repo (a quick grep in the repo for `https://github.com/akasolace/HO` returns a few hits, in particular the links for the check for updates)
- Update current repo to mark it as deprecated, and link to new one

**Comment by wsbrenk** [comment]
Thank @tychobrailleur : added your points to task list.

**Comment by wsbrenk** [comment]
@akasolace do you agree  with first list item?

**Comment by wsbrenk** [comment]
As an alternative to point 1, we could create a new GitHub organization (hattrick-organizer)

**Comment by akasolace** [comment]
Done

**Comment by wsbrenk** [comment]
On the new repo we should enhance the download feature: #1753. @tychobrailleur: What do you think

**Comment by tychobrailleur** [comment]
Just pushed the master branch there:
https://github.com/ho-dev/HO

Need to see how to get all other branches, and the issues from repo.

**Comment by wsbrenk** [comment]
great!

concerning branches - i think only the release branches are useful
issues are very useful
and the actions

**Comment by tychobrailleur** [comment]
Awesome, will look into this tomorrow!

**Comment by wsbrenk** [comment]
I just remember: In the release notes and the change logs I have included links to the milestones. It would be great if we could set them up in the new repo as well.

**Comment by tychobrailleur** [comment]
> great!
> 
> concerning branches - i think only the release branches are useful issues are very useful and the actions

For issues it looks like they can only be “transferred:” https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

Not sure if we want to do this now, or wait a bit?

**Comment by wsbrenk** [comment]
that sounds very tedious, so we should look for better solutions (or program them ourselves;-)

**Comment by wsbrenk** [comment]
@tychobrailleur   [transferring a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) looks like the most easily way. 

As far as i understand this, we have to create a copy of the repo on its origin place (akasolace) that will hold all the stuff that is needed to lead the users to the new place.

**Comment by tychobrailleur** [comment]
I have migrated the Wiki pages too:
https://github.com/ho-dev/HO/wiki

**Comment by akasolace** [comment]
@wsbrenk @tychobrailleur please let me know when the transfer is over I will then archive the HO repository on my account ....

**Comment by tychobrailleur** [comment]
Sure, just need to figure out to transfer issues.  I tried a script, but it
failed, and creates everything under my name

**Comment by akasolace** [comment]
I did it once using pyGithub, I will try to find it ....

**Comment by akasolace** [comment]
Actually no what I had to do was to duplicates issues but simple transfer is supported directly by the API. Strange that you are running into issues ...

**Comment by wsbrenk** [comment]
> please let me know when the transfer is over I will then archive the HO repository on my account ....

Hi akasolace, we had planned to set up your page as a redirection to the new page for a while. at least until most users have moved to the new site via HO update.

**Comment by akasolace** [comment]
I guess it can still be archived and serve that purpose but you will let me know !

**Comment by tychobrailleur** [comment]
> @tychobrailleur [transferring a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) looks like the most easily way.
> 

Yeah, I think you're right.  Copying issues is just not workable with rate limits, and the ownership of issues and comments would be all me, which is not ideal.

Maybe we should just bite the bullet and do it, and then deal with the resulting issues?  

> As far as i understand this, we have to create a copy of the repo at its origin place (akasolace) that will hold all the stuff that is needed to lead the users to the new place.

An empty repo with just a link in the README to the new repo, is that it?

**Comment by tychobrailleur** [comment]
- All the tags are in place right now in the new repo.  Any new release from ho-dev should point there.  I am not sure what the next major version is (HO7?), but that one should be cut off the new repo, and updates will point to new repo.  All good there.
- Old releases will point to old repo, and hardcoded to point to old repo.  Unless somehow we rewrite the URL (I don't know of such mechanism on github, but it looks like your github-foo exceeds mine by far, @wsbrenk), I am not sure how we can get around this.  These are the update URLs:

```java
	public VersionInfo getLatestStableVersion() {
		return getVersion("https://github.com/akasolace/HO/releases/download/tag_stable/version.properties");
	}

	public VersionInfo getLatestVersion() {
		return getVersion("https://github.com/akasolace/HO/releases/download/dev/version.properties");
	}

	public VersionInfo getLatestBetaVersion() {
		return getVersion("https://github.com/akasolace/HO/releases/download/beta/version.properties");
	}

```

One way we could approach this is:
- First make a new release on akasolace repo with a code change where we update the “check the new version logic” to first look at ho-dev, and if nothing, look at akasolace.
- Once that release has been pushed we should be good to migrate.
- At that point we could archive akasolace repo.  Presumably this should keep old releases around.

I am sick at the moment, so my brains are not working very well, so there may very well be gaps in that reasoning, but these are my thoughts right now.

**Comment by wsbrenk** [comment]
@tychobrailleur Get well soon!!!

* the next major version is HO7. it is beta now and still some bug fixes concerning nt teams have to be fixed. when we change the update urls to the new repo, not only the tags have to be in place but also (pre) releases with all the required assets.
* the final version on old repo should point to update urls on new repo. then update requests of older versions can update to exact that version. updating this version will update to newer versions on new repo.
* alternativly we find a way that redirect update urls of the older HO versions to the tags of the new repo (but i don't have any idea, how to do that)
* beautify: i don't know the reason, why the tags are named by different conventions. when we are changing, i would suggest to name them uniquely. either stable, beta, dev or tag_stable, tag_beta, tag_dev. i would prefer the first suggestion.

**Comment by wsbrenk** [comment]
@tychobrailleur how to go on further with this issue?

if there are no further bug reports, i would like to release stable 7.1 in about 2 weeks.
then we could move to the new place.

in this repository (akasolace) i would like to release a stable 7.2 with modified update links to the new place. what do you think about this plan?

**Comment by tychobrailleur** [comment]
> in this repository (akasolace) i would like to release a stable 7.2 with modified update links to the new place. what do you think about this plan?

Yes, that makes sense.

**Comment by wsbrenk** [comment]
as mentioned in #1849, we could do the move of this repository to the new place now (ho-dev if that repo is still a good choice as move target or new repo: hattrick-organizer)

After the move, we should recreate in akasolace/HO all the stuff that is required to lead old HO versions to the new place

- [ ] releases that will do their next update with the new place
- [ ] links of the existing installations (changelog e.g.)

**Comment by wsbrenk** [comment]
@tychobrailleur created a new [github organization](https://github.com/hattrick-organizer) as possible target for the move

**Comment by wsbrenk** [comment]
> Great! You didn't like https://github.com/ho-dev/ ? :-)

I think we should retry a transfer of the repository. If we invoke the github transfer i would hope that issues and pull request will be included.

I don't care if it's called ho-dev or hattrick organizer. So feel free if you will remove the ho-dev repo and restart a transfer or use the new organization. I don't know if we can use anything from the other things in ho-dev?

**Comment by wsbrenk** [comment]
@tychobrailleur do you have admin rights on akasolace/ho. if so, you could invoke the transfer.

i don't see the settings option (anymore).

**Comment by tychobrailleur** [comment]
> @tychobrailleur do you have admin rights on akasolace/ho. if so, you could invoke the transfer.
> 

I don't, that's why I had to push code manually to ho-dev

**Comment by wsbrenk** [comment]
then we should ask @akasolace to [transfer the ho repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository).

**Comment by akasolace** [comment]
Hello, I will have a look now to move the code to ho-dev

**Comment by akasolace** [comment]
ok, so it seems it worked !

**Comment by tychobrailleur** [comment]
> ok, so it seems it worked !

Wow, it also seems to have moved stars and forks, that's amazing!  Thanks a lot for supporting, @akasolace

**Comment by akasolace** [comment]
> > ok, so it seems it worked !
> 
> 
> 
> Wow, it also seems to have moved stars and forks, that's amazing!  Thanks a lot for supporting, @akasolace 

I just had to push a button :/) Thank you @tychobrailleur and @wsbrenk for keeping the project alive !

**Comment by wsbrenk** [comment]
@tychobrailleur the old beta finds the new version. redirection is working perfectly.

![image](https://github.com/ho-dev/HattrickOrganizer/assets/11821502/68a028b2-4717-4404-91b5-bf30efcf8dd0)
