### ISSUE TITLE
Players vanishing from HO

### ISSUE THREAD

**Issue by leschmuh** [ho-dev/HattrickOrganizer#1816]
I am having a strange issue. It has not come with the newest version but I have been having that for a while now... so, sorry for only posting it now.

The following happens: When I open HO, there are three of my players missing in the players list. When I download a new hrf they show up (and they do have a history, e.g. I can see how they skilled etc. - at least palyers 1 and 2 are also in the player analysis togehter with the former players of the team and their recent matches are up to date; player 3 isn't). The three are not the newest players - player 1 is actually from the original team, player 2 was bought early and the third (who is missing in the player analysis) has been bought 1,5 seasons ago (he is correctly listed in the transfer tab...).

I find that extremely strange. And as I said: They do show up, when I make a download (but not if I am importing a downloaded HRF).

This is only and constantly happening with those three players and only in that team. With my first team, everything is fine.

Any ideas?

**Comment by wsbrenk** [comment]
@leschmuh please check the log file of a session where you downloaded the data and closed HO. if you find errors in this log please upload this file.

logs should be in %APPDATA%/HO/logs

**Comment by leschmuh** [comment]
@wsbrenk Thanks for your comment and the hint to look into the log file (could have thought of that mayself). Solution is that I had notes on these players in HT that exceeded 255 signs... shortening the notes solved the problem.


I am uploading the log file just so you can check it if you want to. But my issue is resolved. However, you might think about adapting the size limit in the OWNERNOTES column to match the 500 signs allowed in HT itself.

[HO-1679221007.log](https://github.com/akasolace/HO/files/11010863/HO-1679221007.log)

**Comment by wsbrenk** [comment]
@leschmuh thanks for that info - we will fix that in next version, because the database should not change in version 7 anymore.
