### ISSUE TITLE
[BUG]Incorrect tactic display

### ISSUE THREAD

**Issue by solimar1963** [ho-dev/HattrickOrganizer#1839]
1. If the tactic "play creatively" is selected in the line-up, the tactic is shown as "not available" in the right-hand picture above.
2. In the "opponent check", "play creatively" is also displayed as "not available" in the simulation screen when selecting tactics.

**Comment by wsbrenk** [comment]
does anyone know the formula?

**Comment by solimar1963** [comment]
are the data not transmitted via the CHPP interface?

**Comment by wsbrenk** [comment]
i don't find it in the api docs

**Comment by wsbrenk** [comment]
_
I have a question about Play Creatively. When playing creatively, the outfield players need high passing and experience values, passing is clearly more important (according to the Dev-Blog 4 times as important) and in the case that an outfield player is also unpredictable, his contribution to the tactical strength is doubled. From this you can derive the formula ((PS-Skill*4)+XP) for a non-UB player. For a UB player, the multiplication of 2 is added. You then create this for all 10 field players and get the sum of all 10 players and use the average value of the sum to determine the tactics level.

Now my question is, is there an overview somewhere here of how the tactics level for the creative tactics can be determined? I have already searched for it, but have not found anything.

Does anybody know anything about this?_
