### ISSUE TITLE
[BUG] Subskill recalculation takes a lot of time

### ISSUE THREAD

**Issue by Tarotistas** [ho-dev/HattrickOrganizer#1870]
**Describe the bug**
Subskill recalculation takes a lot of time

**To Reproduce**
1. Go to Training
2. Click on Subskill recalculation
3. Scroll down to bottom right side and see the load bar that literally takes minutes
4. See error (No error)

**Screenshots**

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/65875612/235560581-520b198d-1c2d-414d-92bf-457c714215e9.png">

**Platform information:**
 - OS: [ macOS ]
 - Version (13.3.1 (22E261))
 - HO 7.0

**Additional context**

**Comment by wsbrenk** [comment]
this is, what the warning message box says:

![image](https://user-images.githubusercontent.com/11821502/235742852-6aca785c-9a21-4a01-95f0-ad5db51dd6a6.png)


use the File->subskill recalculation (7 weeks) to get a faster result.

**Comment by Tarotistas** [comment]
Hello! Thanks for replying! I would say I'm not having any warning message. Then I never had to do this workaround. I always press into the icon mentioned. I guess in the Ho 7.0 this function is not working anymore. 

Anyway I did what you asked and works faster. 

In regards the warning message I never came up maybe because I`m running in ES?

Thanks a lot!
BR

**Comment by wsbrenk** [comment]
Find ways to tune performance of subskill recalculation

**Comment by tychobrailleur** [comment]
Just to get  better understanding of this issue: are you saying that performance of that feature have degraded in recent versions, or just that in general it is slow?  This calculation takes longer over time, as the database grows bigger, this is expected, I am just wondering if you're saying that suddenly there is a significant increase in calculation time for no apparent reason?

BTW I also get the alert when triggering the calculation, whether from the menu or from the Training tab:

![Screenshot from 2023-05-07 12-14-32](https://user-images.githubusercontent.com/114285/236674278-c6ce13f7-8c2b-4dc6-96c2-f9c0efd95a33.png)

**Comment by Tarotistas** [comment]
YES, I'm saying I never had to run the subsoil recalculation from MENU and now in HO 7.0v performance have been degraded.

**Comment by masterpatje** [comment]
I did not encounter any problems with the subskill recalculation. Process was done within 1 or 2 minutes.
