### ISSUE TITLE
[BUG] Team-raised heart present in Player details for a recruited player

### ISSUE THREAD

**Issue by tychobrailleur** [ho-dev/HattrickOrganizer#1871]
**Describe the bug**
I just noticed that this player has a heart in the Player details, which in the table means “team-raised”:

![Screenshot from 2023-05-05 19-13-05](https://user-images.githubusercontent.com/114285/236536573-4a179e33-5900-4a34-86b0-cee36f508a16.png)

This happens after looking at a player that was team-raised: the heart does not cleared when visiting a non-team-raised player.

**To Reproduce**
1. Go to Squad tab
2. First select a team-raised player in the list of players 
3. Then Select a non-team-raised player in the list of players
4. Observe that in Player Details tab, the heart that would suggest they are team-raised (loyalty) appears.

**Screenshots**
See above 

**Platform information:**
 - OS: Linux
 - version: 22.1.0

**Additional context**
N/A

**Comment by wsbrenk** [comment]
same as #1901
