### ISSUE TITLE
[BUG] subskill recalculation revisited

### ISSUE THREAD

**Issue by masterpatje** [ho-dev/HattrickOrganizer#1876]
**Describe the bug**
I have a portable version (HO 7.0.479) with HRF files 19 july 2022 onwards.
I downloaded a portable development version (HO 8.0.500) and copied the database files.

When I do a (full) subskill recalculation on HO 7.0.479 the subskill are for me kind of unpredictable.

In the screenshot I give an example where my keeper Jarne Clarebout's subskills changes:
before -> after subskill recalculation
keeper: 14,0 -> 14,8
passing: 7,0 -> 7,48 
scoring: 0,0 -> 0,2

It happens to several players.

**To Reproduce**
download new portable version
copy database from previous version
open new portable version to check if database is correctly copied
open old portable version and do a (full) subskill recalculation

**Screenshots**
HO 7.0.479 after subskill recalculation:
![image](https://github.com/akasolace/HO/assets/102049050/d30a55c2-1a90-42b3-a5b1-d5587b7739ca)

H.O. 8.0.500 without subskill recalculation
![image](https://github.com/akasolace/HO/assets/102049050/74cc20dd-6ecd-4f62-ace6-adaa360e0e5e)

**Platform information:**
 - OS: Windows10
 - Version 7.0.479 / 8.0.500

**Additional context**
Maybe (!) the original database has more data then the added files. That when I installed the portable version that I copied a database from an earlier version. Is there a way to check it? That it has more data than only HRF files 19 July 2022 onwards.

I have a HO 6.1 database that contains a lot more data. If you want I can install another portable version and see what the results are when I do a (full) subskill recalculation on that other portable version?

But please guide me a bit what I can do to do some testing. I know earlier I was always a bit hessistant to use subskill recalculation because I don't fully recognise or understand the end results.

**Comment by masterpatje** [comment]
update:
I just found out that past trainings were set. Most probably meaning that the database was not a clean database when I started to use the portable version in july 2022 and that it not only contains HRF files.

That is maybe also the reason that it gave soms unpredictable (to me) results because the subskill recalculation is making use of match database in combination with past trainings and thus will add subskills as (I think) you told me earlier.

I will start a clean database with development version 8.0.500 and will add 12 HRF files coming 12 weeks and then do the steps again in comparison to a new (development) version and post the results here.

**Comment by masterpatje** [comment]
Oke tested it again. I took a clean database with only 7 HRF files.
Tested 7-weeks and full weeks calculations;
- errors were only margenable 0,01, so all good
- incidentally (one or two players) the amount gained with training was calculated correctly, but the total skill was lower [see screenshots below]

7-weeks recalculation (and afterwards full recalculation)
![image](https://github.com/akasolace/HO/assets/102049050/7bc065f5-b6f3-4de6-ab70-af1b49354035)
no recalculation
![image](https://github.com/akasolace/HO/assets/102049050/339b3efb-be9b-4f62-85d0-54c376ebeab2)

You can close the call or if you want the database or need me to test something please let me know.

**Comment by wsbrenk** [comment]
The "full" recalculation is no longer real full. 

HO 7 uses a limitation of 64 weeks (4 seasons). This is prolonged to 128 weeks in latest HO 8 dev version to better support recalculation of stamina sub.
