### ISSUE TITLE
[BUG]Teamanalyzer choose wrong playfield (home/away)

### ISSUE THREAD

**Issue by crapInhuman** [ho-dev/HattrickOrganizer#1885]
**Describe the bug**
My next match is away, but if i simulate the match, HO set my team as home in the simlation.

**Platform information:**
 - OS: [Windows]
 - Version 7.1 r504

**Comment by wsbrenk** [comment]
so far I can't reproduce this - with my teams the problem doesn't occur

**Comment by UNIKR0N** [comment]
Happens to me too, I'm able to reproduce it and fix it too in HO

Way to reproduce:
1. On the Lineup tab choose a random match or just leave it as it is
2. On the Teamanalyzer tab choose a _different match_ you'd like to analyze
3. The simulation will use the Lineup tab's match home/away information

Steps to fix:
1. On the lineup tab choose the right match
2. Choose the same match in the TeamAnalyzer
3. The simulation should now have the proper home/away teams

**Comment by tychobrailleur** [comment]
I am currently working on that plugin, I'll look into this one.
