### ISSUE TITLE
[FEATURE] Improve trainings planning

### ISSUE THREAD

**Issue by wsbrenk** [ho-dev/HattrickOrganizer#1886]
Feedback from HT forum:

One very good improvement is the training management where we can now define complex training for one player (ie: a player can be set to be trained in several skills in training tab).

What would be awesome would be to be able to configure each player to tell "this player will be trained in that skill and that other skill, but not that one, every time".

Let's say I plan to train playmaking and defense for next two seasons.
First season is planed for defense, I set up each non-def to be trained in defense next season.
Second season is planed to be playmaking, I set up each non-middlefield to be trained in playmaking that second season.
That's (very ; ) great but the issue is if I want to check what would be the progression of my team if I invert the training of these two seasons, I'll have to set up again each player for each week according to the changes made in the training plan.

That's long. And for now, that's not too clearly shown in training tab why each player is tagged as receiving training.

So, having a window for each player (like the window to set decimals on each skill) where we could check one box per skill to tell HO this player will be trained in that skill every training session dedicated to that skill, that would improve the stuff drastically. At least, that's what I think :p

**Comment by wsbrenk** [comment]
Training plan should provide checkboxes (full training, partial training, osmosis training an individual training) for each player and each skill.

Individual (weekly) planned training should get precedence to the checkbox settings.

**Comment by wsbrenk** [comment]
![image](https://github.com/ho-dev/HattrickOrganizer/assets/11821502/92d37600-d5de-44f3-821b-1134f10f61ea)

**Comment by mathias213** [comment]
Hi wsbrenk : )

First, a huge thank you for that feature which shall be great to plan complex training. I was the one on the forum requesting for that feature (so, thanks again ; )

Issue: Setting a training plan for several skills is lost on HO restart.
When setting a training plan for several skills for one player, once HO is restarted, only the last training plan which was set is there, training plans for others skills are lost.
