### ISSUE TITLE
[FEATURE] Market Value

### ISSUE THREAD

**Issue by masterpatje** [ho-dev/HattrickOrganizer#1910]
Hattrick announced kn its 26th birthday that it has or is going to add information on players market value. Everytime there is a relevant increase or decrease in skill the average market value will be taken.

I know in HO there is a field which is no longer in use that had this market value information or transfer worth.

Could you look if the information is available in the HRF files and could it be added?

**Comment by wsbrenk** [comment]
same as #1594
