### ISSUE TITLE
HRF download not working anymore

### ISSUE THREAD

**Issue by emar9** [ho-dev/HattrickOrganizer#1917]
**Describe the bug**
An error occured when trying to download the hrf file

**To Reproduce**
1. Go to 'File'
2. Click on 'Download' in the menu
3. Click on  button 'Download'

**Screenshots**
[
<img width="1439" alt="Bildschirmfoto 2023-09-09 um 15 04 47" src="https://github.com/ho-dev/HattrickOrganizer/assets/51410121/04345e07-7f6d-4226-899c-b6f6d2a8a57b">
](url)

**Platform information:**
 - OS: macOS 
 - Version 12.6.8 (21G725)

**Additional context**

**Comment by wsbrenk** [comment]
#1914 duplicate
