### ISSUE TITLE
[FEATURE] new chpp file versions

### ISSUE THREAD

**Issue by wsbrenk** [ho-dev/HattrickOrganizer#1927]
Changelog
2023-09-07
[players - 2.6](https://www86.hattrick.org/Community/CHPP/NewDocs/File.aspx?name=players)
Note: Removed non-player trainers (now added it to the staff list) and replaced TrainerSkill with TrainerSkillLevel, for player trainers only.
Added Output: TrainerSkillLevel
Removed Output: TrainerSkill
[playerdetails - 3.0](https://www86.hattrick.org/Community/CHPP/NewDocs/File.aspx?name=playerdetails)
Note: Removed non-player trainers (now added it to the staff list) and replaced TrainerSkill with TrainerSkillLevel, for player trainers only.
Added Output: TrainerSkillLevel
Removed Output: TrainerSkill
[staffavatars - 1.1](https://www86.hattrick.org/Community/CHPP/NewDocs/File.aspx?name=staffavatars)
Note: Added trainer avatar
Added Output: Trainer
Added Output: TrainerId
Added Output: Avatar
Added Output: BackgroundImage
Added Output: Layer
Added Output: Image
[stafflist - 1.2](https://www86.hattrick.org/Community/CHPP/NewDocs/File.aspx?name=stafflist)
Note: Added all trainer info
Added Output: Trainer
Added Output: TrainerId
Added Output: Name
Added Output: Age
Added Output: AgeDays
Added Output: ContractDate
Added Output: Cost
Added Output: CountryID
Added Output: TrainerType
Added Output: Leadership
Added Output: TrainerSkillLevel
Added Output: TrainerStatus

**Comment by pencil** [comment]
This seems to break download of trainer info for my team (trainer is externally recruited non-player):

![image](https://github.com/ho-dev/HattrickOrganizer/assets/812086/0b1fac0f-df96-4bcc-b0da-94e72cb45cee)

**Comment by wsbrenk** [comment]
@pencil:  bad - i can not debug this with my teams - could you provide your database backup.

**Comment by pencil** [comment]
I think it has to do with my trainer being externally recruited (i.e. he was never a player). The API call in the screenshot does not seem to work in that case. I'll come back and add a database snapshot soon™ but I don't know how useful it will be without you having access to an affected account.

**Comment by wsbrenk** [comment]
@pencil would be great if you could test again with latest dev version. if it is still not working your database backup would help. With that i can try to debug your downloads. After my test you can reset your HO oauth setting to disable downloads by me.

**Comment by pencil** [comment]
Sorry for the delay here! I just tested with 8.0.550.0 and it seems to work now. Thank you! <3
