### ISSUE TITLE
[BUG]Automatic set up

### ISSUE THREAD

**Issue by solimar1963** [ho-dev/HattrickOrganizer#1930]
If I deselect players in the "Lineup" tab in the player overview so that they are not included in the automatic lineup, and then press the "OK" button, the checkmarks are set for the previously deselected players and they are included in the lineup after all. 

If I reset the lineup completely with the "Clear all positions" button, the previously deselected players are also reactivated.

In addition, the heading "Auto lineup" is missing.

**Comment by wsbrenk** [comment]
@solimar1963 thank you for reporting this issue. What HO version you are using?

**Comment by solimar1963** [comment]
2023-10-13 15:05:36 [Info]    core.HO: VERSION: 7.3   versionType:  RELEASE   RevisionNumber: 523

**Comment by wsbrenk** [comment]
@solimar1963 i cannot reproduce this with my team. if you would upload a backup of your database i could try to debug this issue.

**Comment by solimar1963** [comment]
[db_user-2023-10-20.zip](https://github.com/ho-dev/HattrickOrganizer/files/13054170/db_user-2023-10-20.zip)

**Comment by wsbrenk** [comment]
thanks - now i can reproduce it
