### ISSUE TITLE
[BUG] PoEditor HO translation project is archived

### ISSUE THREAD

**Issue by wsbrenk** [ho-dev/HattrickOrganizer#1944]
same procedure as every year - again the HO translation project is archived and no longer accessible by github actions.

Contacted POEDITOR support.

**Comment by tychobrailleur** [comment]
Thanks for dropping that note, @wsbrenk I was scratching my head as to why [this job ](https://github.com/ho-dev/HattrickOrganizer/actions/runs/6920389202/job/18824837651)was failing.  Will wait until this gets resolved.

**Comment by wsbrenk** [comment]
the project is restored. 

@akasolace could you please move the poeditor project to my account. Hopefully than it will stay a little longer;-)

Von: Anamaria Mocanu <info@poeditor.com> 
Gesendet: Montag, 20. November 2023 16:58
An: wolfgang.schneider@zissener-weg-brenk.de
Betreff: Re: AW: Contact POEditor

Thank you for your reply.

Would it possible to get in touch with Thisisakasolace ([thisisakasolace@gmail.com](mailto:thisisakasolace@gmail.com)) and ask him to log in to his POEditor account and transfer the project ownership to you? This would be the easiest way to transfer ownership of the project to your account, following the steps here: https://poeditor.com/kb/how-to-move-project-another-account 

Best regards,
Anamaria Mocanu 
POEditor.com

**Comment by wsbrenk** [comment]
newest english.properties are not yet pushed to poeditor

**Comment by akasolace** [comment]
hello @wsbrenk I am about to do it but I got the following warning
do you want me to proceed or do you want to investiguate first ? 

![image](https://github.com/ho-dev/HattrickOrganizer/assets/1136496/025e4123-4b94-4189-9535-7676080a7074)

**Comment by wsbrenk** [comment]
@akasolace do you pay for your poeditor account? I'm using the free "plan". I modified my profile setting a little: Give translation memory access to all contributors. Maybe that will fix the message you displayed. 
If not, i would accept to send the request. Hopefully no active contributors will be kicked out. There are a lot inactive contributors which can lose access.

If that does not work anymore - we should search another solution for the translation job.

**Comment by akasolace** [comment]
@wsbrenk I did not pay, but it was a special open source plan ... I can't have a look at it right now but I will do that asap

**Comment by wsbrenk** [comment]
sync between github language file (english) and poeditor is not working

**Comment by wsbrenk** [comment]
Today I imported the English properties into the Poeditor project by hand, because the automatic integration doesn't work at the moment.
This will allow us to start the translations if we want to start the beta phase for an HO8 in the next few weeks.

**Comment by wsbrenk** [comment]
Again the poeditor project is not reachable - mail to support is sent.

**Comment by wsbrenk** [comment]
In Settings->webhook i found: 

Response 404
 Completed in 0.5 seconds.
Headers
Content-Length: 22
Content-Type: text/html; charset=UTF-8
Date: Sun, 25 Aug 2024 17:52:47 GMT
Server: Apache/2.4.52 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Body
Error: Invalid webhook


Request URL: https://api.poeditor.com/webhooks/2fdbd5777f
Request method: POST
Accept: */*
Content-Type: application/x-www-form-urlencoded
User-Agent: GitHub-Hookshot/e583c15
X-GitHub-Delivery: 49c81f12-6322-11ef-9eff-1eebcca6146a
X-GitHub-Event: push
X-GitHub-Hook-ID: 78736591
X-GitHub-Hook-Installation-Target-ID: 151943384
X-GitHub-Hook-Installation-Target-Type: repository

**Comment by wsbrenk** [comment]
In the meantime, it occurred to me that we could create a new project at poeditor and import the property files of the current project there. The translators would then all have to register again.

**Comment by wsbrenk** [comment]
@akasolace transfered the poeditor project now and i confirmed the request. Now we are waiting for the poeditor confirmation.

**Comment by wsbrenk** [comment]
The transfer is finished. Let's check if the webhook now again is working.

**Comment by wsbrenk** [comment]
![image](https://github.com/user-attachments/assets/4f887aab-f0de-4699-8c4c-c19f4a6d437a)

**Comment by wsbrenk** [comment]
webhook created and edited on  github side - new terms arrived at poeditor side
