### ISSUE TITLE
Menu Functions reset when closing the program[BUG]

### ISSUE THREAD

**Issue by theobserver** [ho-dev/HattrickOrganizer#1954]
**Describe the bug**
Hi all.
Thank you for your work on this amazing app.
I am not sure if this is a bug or it is meant to be this way and it is not critical but I post it anyway:

When i start the program, transfers function/Tab F7 is closed by default.
If i open it, it appears. If you close HO and reopen it e.g. the next day, transfers tab is closed again. You have to open it again and so on.
Should not the program remember which tabs were open when it closed and remember it?

**To Reproduce**
1. Open HO
2. Press F7, the transfers tab opens.
3. Close HO.
4. Open HO. Transfers Tab is closed, you have to reopen it.

**Screenshots**
-

**Platform information:**
 - OS: Windows
 - Version 7.3 Build 523

**Additional context**
Thank you fo your time reading this.

Regards,
Nik.

**Comment by wsbrenk** [comment]
@theobserver please have a look at menu File->Settings->Modules
There you can set module transfer to autostart.

**Comment by theobserver** [comment]
Thank you .
Much obliged.
