### ISSUE TITLE
[FEATURE] Ideas for a bycatch while porting to Kotlin:

### ISSUE THREAD

**Issue by wsbrenk** [ho-dev/HattrickOrganizer#1962]
* make all ui tables (jtable) to new class HOTable using HOTableModel implementing the common things of save and restore layout, sorting and so on.
* add toggling of background row color to the HOTableModel
* code conventions concerning naming
  * load/store for database access
  * upload/download for chpp access
  * get/set the other kind of access 

to be continued

**Comment by tychobrailleur** [comment]
I was also thinking of spending some time to separate frontend and backend/db accesses to see if we can one day migrate to JFX or another UI technology.

**Comment by wsbrenk** [comment]
More usage of type safe enums instead of ints (e. g. PlayerSkill).

**Comment by wsbrenk** [comment]
ideas should be moved to extra tickets.
