### ISSUE TITLE
[BUG] permission access error from task ':poeditorPull'

### ISSUE THREAD

**Issue by armandoschianodicola** [ho-dev/HattrickOrganizer#1977]
**Describe the bug**
permission access error from task ':poeditorPull' while building project locally in Intellij. I would like to build the project in local in order to contribute.

**To Reproduce**
1.  set POEDITOR_APIKEY as env variable in edit configuration with api key from poeditor website
2. build project

or 

2. run project with the same env variable

**Screenshots**
![image](https://github.com/ho-dev/HattrickOrganizer/assets/12221076/0eba06b1-c9e0-4f38-b3e3-821c1264d3d7)

**Platform information:**
 - OS: ubuntu

**Comment by armandoschianodicola** [comment]
I tried that configuration but the problem remains. 

It seems like the api key I generated from the poeditor website does not have sufficient permissions to pull translations from poeditor website to my local machine when I tried to build.  

![Schermata del 2023-11-15 11-33-57](https://github.com/ho-dev/HattrickOrganizer/assets/12221076/b43b3571-8709-4375-aec1-4b46ada4a30f)

![image](https://github.com/ho-dev/HattrickOrganizer/assets/12221076/af2e0ff1-e7c6-4848-849b-944a0ce0dca2)

**Comment by armandoschianodicola** [comment]
I tried that configuration but the problem remains. Is it possible that the problem lies with the poeditor api key? the error says I do not have access to poeditor resources when pulling.

![Schermata del 2023-12-09 23-43-06](https://github.com/ho-dev/HattrickOrganizer/assets/12221076/465ac1f4-ee9c-4bb4-b658-14e1950c34ef)

![Schermata del 2023-12-09 23-57-47](https://github.com/ho-dev/HattrickOrganizer/assets/12221076/9741fbd4-7efb-4592-bc23-7f6ded4c5933)

**Comment by wsbrenk** [comment]
i hoped, that using the settings i showed would prevent building with gradle. Gradle is only required in final github release builds.

**Comment by armandoschianodicola** [comment]
After some attempts I finally managed to build with Intellij avoiding Gradle build. Thanks
