### ISSUE TITLE
[FEATURE] Upgrade HO to Gradle 8.5

### ISSUE THREAD

**Issue by tychobrailleur** [ho-dev/HattrickOrganizer#1988]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**
Upgrade HO to use Gradle 8.5.

**Additional context**
This is already proving difficult as the poeditor plugin is incompatible with Gradle 8.5.  I have however a local version that works.  As a side note, I will also clean up the build file, hopefully following most of the [recommended practices](https://docs.gradle.org/current/userguide/authoring_maintainable_build_scripts.html).

**Comment by tychobrailleur** [comment]
First pass there: https://github.com/ho-dev/HattrickOrganizer/compare/master...feature/gradle_upgrade

I haven't been able to test the POEditor pull, my API key won't let me do that.  Of interest is probably our own `build.gradle` and the changes there.  I want to make sure you're happy with them, @wsbrenk 

One thing to note is that now `./gradlew run` works out of the box, which is nice for newcomers.

**Comment by wsbrenk** [comment]
@tychobrailleur I wouldn't have dared to do that so quickly - it's good that you're doing that!

**Comment by wsbrenk** [comment]
Could there be side effects in the update process or will nothing change (also for HO V3 users)?

**Comment by tychobrailleur** [comment]
> @tychobrailleur I wouldn't have dared to do that so quickly - it's good that you're doing that!

It's the recent report on the Gradle issue that encouraged me to finally bite the bullet, as this is something I have been meaning to do in a while, cleanup that file.  Did I mention I hate Gradle with a passion? :-)

If you think this is so premature, I can hold off on this.   For example, we can tackle this post 8.0 release, there is no rush.

**Comment by tychobrailleur** [comment]
> Could there be side effects in the update process or will nothing change (also for HO V3 users)?

You mean the automated update process within HO?  I don't believe so, the output of the Gradle build should be the same.  Right now I can't get to the end of the build because I have no Install4j license, and the POEditor files are not downloading for me...

**Comment by wsbrenk** [comment]
@tychobrailleur Concerning install4j i can provide the key. Don't know, what to do in poeditor - i will have a look

**Comment by tychobrailleur** [comment]
I am sure you've noticed this is now merged, let me know if you spot any issue.  I have preserved past behaviour of deleting DB and downloading languages files, even in dev, but I am thinking of making these optional in the future.

@armandoschianodicola This should address some of your issues, hopefully.  Let us know how you are getting on, and looking forward to your contributions!

**Comment by wsbrenk** [comment]
@tychobrailleur I've gotten used to waiting for a 2-week test period after the Merge. If no one complains, the ticket will be closed.

**Comment by armandoschianodicola** [comment]
> I am sure you've noticed this is now merged, let me know if you spot any issue. I have preserved past behaviour of deleting DB and downloading languages files, even in dev, but I am thinking of making these optional in the future.
> 
> @armandoschianodicola This should address some of your issues, hopefully. Let us know how you are getting on, and looking forward to your contributions!

Thanks. I tried to build with Gradle: the poeditorPull now runs smoothly, but I got two tests failed (see attachments)

![Schermata del 2023-12-21 17-29-36](https://github.com/ho-dev/HattrickOrganizer/assets/12221076/5a7f26c9-b934-4ef0-ac97-2063e68cbac5)

![Schermata del 2023-12-21 17-28-59](https://github.com/ho-dev/HattrickOrganizer/assets/12221076/e693c057-e956-4645-a27b-0afa7833d96a)


I would like to fix with a PR but I do not know which is wrong: the expected value from the test or the actual return from the method.

**Comment by tychobrailleur** [comment]
The former: it doesn't take into account the fact that the value returned by this method is locale-dependent.

**Comment by armandoschianodicola** [comment]
> The former: it doesn't take into account the fact that the value returned by this method is locale-dependent.

I opened the PR https://github.com/ho-dev/HattrickOrganizer/pull/2009 for this issue. My proposal was to refactor the expected test value with some  dynamic string formatting, since the methods for locale-aware number formatting were so well nested inside Helper functions that could not be controlled at a higher level. 

This is the best solution I have come up with so far. Any improvements is welcome!
