### ISSUE TITLE
[BUG] DB problems

### ISSUE THREAD

**Issue by lateralegialla** [ho-dev/HattrickOrganizer#2012]
**Describe the bug**
during the opeing of HO app, the Database has some problems and the app don't start

**To Reproduce**
1. i had this problem with HO 6.2 
2. after some days i tryed to install HO 7.2
3. the problem remain the same

**Platform information:**
 - OS: Windows 
 - Version win 11 pro
 - 
[db vecchio.zip](https://github.com/ho-dev/HattrickOrganizer/files/13943061/db.vecchio.zip)

**Comment by wsbrenk** [comment]
Hi @lateralegialla 
there are backups (zip files) of your database files in your database folder. Please first try to restore them and check if that would fix your problems. There are a least 3 files required by the HO database.

.script, .data and .properties

If that does not work upload one of your backups and we could try to debug your issue.

**Comment by lateralegialla** [comment]
how i can restore? i have these 3 files too.

**Comment by wsbrenk** [comment]
double clicking the zips will open them. You can drag the containing files to your database folder and overwrite the existing files. If there are more than 3 files (.log and tmp) then your database was not closed correctly and this could be the cause of your problems.

**Comment by lateralegialla** [comment]
ok, if i move out, the 3 old files HO starts. 
i don't know which if them causes the error. 
can you help me with the log file of first error i had long time ago?
[HO-2023-11-06.log](https://github.com/ho-dev/HattrickOrganizer/files/13943391/HO-2023-11-06.log)

**Comment by wsbrenk** [comment]
this is an error reading the economy database table. For me it looks like an database error. I fear your database is corrupted.

**Comment by lateralegialla** [comment]
ah ok, so i have to begin with another DB. how can i have always a DB saved and avoid this problem?

**Comment by wsbrenk** [comment]
HO automatically creates 3 backups (zip-files) in your database folder.

**Comment by lateralegialla** [comment]
ok. now i have backups.
about the past, do you think i can recover data in some way?

thank you very much for the support. (next time i will open a bug here soon)

**Comment by wsbrenk** [comment]
if you will restore a valid backup (replace the existing database files (.data, .script and .properties) by the contents of one backup zip) all historical data should be recovered. Then there is no need to reload them from Hattrick (F12) or from hrf files that were saved by you in the past.
if you are not able to restore your zips, you can recover some historical data (matches e. g.) with HO download functions. But there is no option to reload historical training settings. These are lost and have to be reset by hand.

**Comment by lateralegialla** [comment]
i don't have other backup or hrf files. i have to lunch HO like admin to save backup files and i never did before. i start now, good for the future but not for the past :).
thank you very much. 
the bug can be closed.
