### ISSUE TITLE
[BUG][8.0.583.0] New per skill training plan memorizing only one skill

### ISSUE THREAD

**Issue by mathias213** [ho-dev/HattrickOrganizer#2013]
**Describe the bug**
In "Training" tab, the [really great, a big thanks for that ; )] new per skill plan is storing in database only the last skill set. All other are forgotten once HO is restarted.

**To Reproduce**
1. Go to 'Training' tab
2. Click on drop-down menus to set training per skill (set up several per skill training)
3. Close HO
4. Reopen HO
5. Go to Training tab
6. Check per skill training plan => only one is set

**Screenshots**

**Platform information:**
 - OS: Linux
 - Version: 8.0.583.0

**Thanks again**
This feature is absolutely great! Thank you for developing it so quickly ; )

**Comment by wsbrenk** [comment]
thanks for testing
