### ISSUE TITLE
[BUG] First Portable Installation missed CHPP link

### ISSUE THREAD

**Issue by mistermax80** [ho-dev/HattrickOrganizer#2016]
**Describe the bug**
First Portable Installation missed CHPP link

**To Reproduce**
On new portabile installation

**Screenshots**
![image](https://github.com/ho-dev/HattrickOrganizer/assets/15519907/461dc8cc-bcfe-4009-b7aa-1602160cc2a9)

**Platform information:**
 - OS: Windows
 - Version 7.3 523

**Comment by tychobrailleur** [comment]
Wow, welcome back, long time no see!  ;-) 

This could be an issue with OAuth, somehow.  Would you be able to include the logs to see if there is anything in there?  Also, you mention “First portable installation” -- does it mean it worked subsequently?

**Comment by mistermax80** [comment]
hi mates, nice to see!!!!
I need this error:
![image](https://github.com/ho-dev/HattrickOrganizer/assets/15519907/9aa027db-11fe-4c6d-a17b-cf8324169e8f)

`2024-01-30 12:58:33 [Info]    core.model.HOVerwaltung: language used for interface is: Italiano
2024-01-30 12:58:33 [Info]    core.gui.HOMainFrame: This is HO! version 7.3, have fun!
2024-01-30 12:58:33 [Info]    core.gui.HOMainFrame: Operating system found: Windows 10 on amd64 (10.0)
2024-01-30 12:58:33 [Info]    core.gui.HOMainFrame: Using java: 17.0.3 (Eclipse Adoptium)
2024-01-30 12:58:34 [Warning] module.lineup.Lineup: no match to determine location
2024-01-30 12:58:41 [Error]   core.net.login.OAuthDialog: Exception in obtainUserCode: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-01-30 12:59:46 [Info]    core.gui.HOMainFrame$1: shutting down HO... 
2024-01-30 12:59:46 [Info]    core.gui.HOMainFrame: Shutdown complete! isAppTerminated: true
2024-01-30 12:59:47 [Info]    core.gui.HOMainFrame$1: exiting...`

**Comment by tychobrailleur** [comment]
This seems to be the same TLS error as #1939 all right.  Are you behind a VPN, a firewall, or a network proxy, by any chance?

From memory, we use the JVM CA certs to connect to CHPP, and CHPP's cert is signed by DigitCert:

```
$ gnutls-cli chpp.hattrick.org:443  
Processed 165 CA certificate(s).
Resolving 'chpp.hattrick.org:443'...
Connecting to '193.34.188.182:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=*.hattrick.org', issuer `CN=GeoTrust TLS RSA CA G1,OU=www.digicert.com,O=DigiCert Inc,C=US', serial 0x063b277c459de09b6b31aef1d183f6d1, RSA key 2048 bits, signed using RSA-SHA256, activated `2023-06-16 00:00:00 UTC', expires `2024-07-16 23:59:59 UTC', pin-sha256="vlI4ul53jbtra6cy00owfSDKINz8T4w/FHtLPx4EleM="
	Public Key ID:
		sha1:f37604d07216afe1fdda02e88eaf2e266bb94c88
		sha256:be5238ba5e778dbb6b6ba732d34a307d20ca20dcfc4f8c3f147b4b3f1e0495e3
	Public Key PIN:
		pin-sha256:vlI4ul53jbtra6cy00owfSDKINz8T4w/FHtLPx4EleM=

- Certificate[1] info:
 - subject `CN=GeoTrust TLS RSA CA G1,OU=www.digicert.com,O=DigiCert Inc,C=US', issuer `CN=DigiCert Global Root G2,OU=www.digicert.com,O=DigiCert Inc,C=US', serial 0x0d07782a133fc6f9a57296e131ffd179, RSA key 2048 bits, signed using RSA-SHA256, activated `2017-11-02 12:23:37 UTC', expires `2027-11-02 12:23:37 UTC', pin-sha256="SDG5orEv8iX6MNenIAxa8nQFNpROB/6+llsZdXHZNqs="
- Status: The certificate is trusted. 
- Description: (TLS1.2-X.509)-(ECDHE-X25519)-(RSA-SHA256)-(AES-256-GCM)
- Session ID: 94:18:00:00:06:CA:2F:2F:31:29:8B:E6:64:3E:96:4D:DA:9A:2B:5B:B0:2E:E5:A4:9A:0B:29:A0:1F:0E:6C:F0
- Options: extended master secret, safe renegotiation, OCSP status request,
- Handshake was completed
```

And that root CA definitely is the cacerts bundle part of 17.0.3 Eclipse Temurin:

![Screenshot from 2024-01-30 19-29-14](https://github.com/ho-dev/HattrickOrganizer/assets/114285/44c696b5-791e-4690-a340-8bcdac2d7f97)

Reason this could fail, however, like in #1939 is if you're behind a work proxy which re-encrypts all traffic using an internal CA.

**Comment by tychobrailleur** [comment]
This seems to be the same TLS error as #1939 all right.  Are you behind a VPN, a firewall, or a network proxy, by any chance?

From memory, we use the JVM CA certs to connect to CHPP, and CHPP's cert is signed by DigitCert:

![Screenshot from 2024-01-30 20-48-08](https://github.com/ho-dev/HattrickOrganizer/assets/114285/904ba985-199a-4f42-8c2f-4bbbe5809712)



And that root CA definitely is the cacerts bundle part of 17.0.3 Eclipse Temurin:

![Screenshot from 2024-01-30 19-29-14](https://github.com/ho-dev/HattrickOrganizer/assets/114285/44c696b5-791e-4690-a340-8bcdac2d7f97)

Reason this could fail, however, like in #1939 is if you're behind a work proxy which re-encrypts all traffic using an internal CA.

**Comment by mistermax80** [comment]
So, I think some limitation, Im trying on business laptop. I will try run with admin right.

**Comment by tychobrailleur** [comment]
@mistermax80 It's not really a permissions issue, more of a network one.  One way to solve this would be to prompt the user with the cert that is being used, and ask that user whether to accept it, but in 99% of cases, the user would not be able to tell whether or not this is a safe cert to accept, so I am erring on the “this is a limitation” side all right.

**Comment by mistermax80** [comment]
So, in my case, i should accept the limitation and I will not install HO...
I think, if I take the risk if accept or no, by an force beviour.

**Comment by tychobrailleur** [comment]
Closing this as per https://github.com/ho-dev/HattrickOrganizer/issues/2016#issuecomment-1925204763
