### ISSUE TITLE
[FEATURE] Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by wsbrenk** [ho-dev/HattrickOrganizer#2019]
[release-dev](https://github.com/ho-dev/HattrickOrganizer/actions/runs/7777099403/job/21205019442)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-java@v3, gradle/wrapper-validation-action@v1, ClementTsang/delete-tag-and-release@v0.3.1, softprops/action-gh-release@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by wsbrenk** [comment]
One action missing:

* softprops/action-gh-release@v1.

**Comment by tychobrailleur** [comment]
As a temp measure you can use softprops/action-gh-release@<sha-1 commit>

**Comment by tychobrailleur** [comment]
Now completed
