### ISSUE TITLE
[FEATURE] Improve team analyzer tab

### ISSUE THREAD

**Issue by tychobrailleur** [ho-dev/HattrickOrganizer#2020]
- Solve the weird button locking when downloading details
- Add some information panel that gives some details about the selected team
- Make Special Events optional through a module parameter (on by default)

Ongoing work there: https://github.com/ho-dev/HattrickOrganizer/tree/feature/improve_ta

**Comment by tychobrailleur** [comment]
Here is the current look, still working to get a better UX:

![Screenshot from 2024-02-25 13-27-14](https://github.com/ho-dev/HattrickOrganizer/assets/114285/befb0825-7a40-4629-a497-b16a19722790)


Things to note:
- Current streak will be shown with bullets of colour, like in the table in the "Series" tab
- Position will be correct :-)  For this and the previous item to work, there will be additional requests required
- I have moved the Update button beside the Analyse one 
- I am trying to figure out why not all columns in the match table are populated.
- Also, there is a number (called "apperance") beside each player's name, but I don't know what it does; I'll try to figure it out.


Feedback and comments more than welcome!

**Comment by wsbrenk** [comment]
> Also, there is a number (called "apperance") beside each player's name, but I don't know what it does; I'll try to figure it out.

I think this is the number of matches the player played within the list of selected matches (when the average row is selected).

**Comment by wsbrenk** [comment]
@tychobrailleur do you want to continue working on this ticket? If so - shall we release it with HO8 or should we postpone it to new tickets in milestone for HO9?

**Comment by tychobrailleur** [comment]
> @tychobrailleur do you want to continue working on this ticket? If so - shall we release it with HO8 or should we postpone it to new tickets in milestone for HO9?

Yes, I want to continue on this one, but I'd like to have some users' feedback.  Maybe we can close this one -- and release with HO8 as is, and create a new one for further improvements for HO9.  How does that sound?

**Comment by wsbrenk** [comment]
@tychobrailleur sounds good to me. So let us start the beta phase and maybe there will be some feedback and we could decide if we realize that in HO8.0, HO8.1 or HO9.
