### ISSUE TITLE
[FEATURE] Youth player future trainings development

### ISSUE THREAD

**Issue by wsbrenk** [ho-dev/HattrickOrganizer#2035]
Show future training development of youth players, which is calculated by the potential calculation.
Take the scouts allrounder information into account.

**Comment by masterpatje** [comment]
I saw the thread. Maybe better InitialOverallSkills or ScoutedOverallSkills? Because the overall skills will change and they are the initial overall skills on the moment that the scout discovers the youth player. 

See this as food for thought. Dont know if its helpfull.

**Comment by wsbrenk** [comment]
@masterpatje this overall skills level is defined as the average of the 3 highest start and max skills of the youth player. For example:

Skill|Start|Max
-|-|-
keeper|1|1
defending|3|5
playmaking|2|4
wing|4|7
passing|3|4
attack|2|3

=> overallskill = (4+7+3+5+3+4)/6 = 26/6 = inadequate
