### ISSUE TITLE
[BUG] error message after clean install after images are downloaded

### ISSUE THREAD

**Issue by masterpatje** [ho-dev/HattrickOrganizer#2044]
**Describe the bug**
After doing a fresh install and when HO finishes the downloading of the images I don't see the faces in the latest version.
When I click on the silver bar:
![image](https://github.com/ho-dev/HattrickOrganizer/assets/102049050/f95a44aa-325c-4fee-a986-ef7ecc9e4748)
I get the following error.
![image](https://github.com/ho-dev/HattrickOrganizer/assets/102049050/52ba7a16-ed2d-468a-94af-a84f5d9ad63c)

I was trying to add players to the right squad (A t/m E) and noticed that I was unable to. I didn't have this with previous versions.

**Platform information:**
 - OS: Windows10
 - Version 8.602

**Comment by wsbrenk** [comment]
@masterpatje Workaround is restarting HO. I will try to fix this.
