### ISSUE TITLE
[BUG] hrf bulk import can generate multiple trainings in the same week

### ISSUE THREAD

**Issue by dominiquelee** [ho-dev/HattrickOrganizer#2050]
**Describe the bug**
Fresh install of HO 7.3.523.2. Download today's hrf. Manually import successfully 355 historical hrfs from 2019 to 2024 all at once (with hrfs that can cover the same week).
![hrfs](https://github.com/ho-dev/HattrickOrganizer/assets/1204726/9440975b-3dcd-4b3a-bf30-d0a34a416e1f)
Each of the hrfs seems to generate an entry in past trainings, and the default undefined entry is not deleted:
![pasttrainings](https://github.com/ho-dev/HattrickOrganizer/assets/1204726/2bd43eb9-c2e9-4f8a-82cc-16dcc1a4d6fe)

Subskill recalculation seems to believe all my players trained in Scoring are now x.99 after the training from the 4/5, so I think they are all taken into account.

**Platform information:**
 - OS: Windows
 - Version 7.3.523.2

**Comment by wsbrenk** [comment]
looks similar to this one #2029

**Comment by dominiquelee** [comment]
That's indeed fixed in 8.0.607.0, not sure how I missed the previous report, sorry for the noise!
