### ISSUE TITLE
[QUESTIOn]

### ISSUE THREAD

**Issue by masterpatje** [ho-dev/HattrickOrganizer#2051]
Is it possible to set multiple future trainings at once? Or an easy way to change all future trainings to a specific new type?

**Comment by wsbrenk** [comment]
yes - you can select multiple rows in future training table, then push the button "edit selection". A dialog appears that let you edit the training parameters for all selected lines (training weeks).

**Comment by tychobrailleur** [comment]
(BTW there is a [Q&A](https://github.com/ho-dev/HattrickOrganizer/discussions/categories/q-a) section in HO Discussions)
