### ISSUE TITLE
[BUG] Opening the team analyzer takes longer than 20 sec

### ISSUE THREAD

**Issue by wsbrenk** [ho-dev/HattrickOrganizer#2055]
If I analyze this correctly, a lot of information is downloaded from hattrick as soon as I start the analyzer. 
Especially the loading of the logo of the selected team takes a very long time.

~~~
        // Column 1
        val infoLabel = JLabel()
        infoLabel.icon = ImageIcon(details["LogoURL"])
~~~

**Comment by tychobrailleur** [comment]
That's odd, I don't see the dramatic delay you're experiencing, even after deleting the db and starting afresh.

On a side note, the label you're pointing to is not used yet, so it can be removed. I can create a PR.

**Comment by tychobrailleur** [comment]
Ah looks like you beat me to it by the time I finished typing this ob my phone 😁

**Comment by wsbrenk** [comment]
@tychobrailleur it seems to be a special problem with my first team - the unused logo download takes the long time and doesn't return any logo at all.

**Comment by wsbrenk** [comment]
@tychobrailleur what do you think about storing the cached team details of opponent teams in the database and starting downloads only on explicite user actions which should not be the opening of the main panels?

**Comment by tychobrailleur** [comment]
Yes, I think that's the right way to go.  And agree with the HO9 target.  I can work on this.

**Comment by tychobrailleur** [comment]
> @tychobrailleur it seems to be a special problem with my first team - the unused logo download takes the long time and doesn't return any logo at all.

Ah that could be it, it probably hangs until the request times out!
