### ISSUE TITLE
[BUG]import of youth games breaks

### ISSUE THREAD

**Issue by gerste2020** [ho-dev/HattrickOrganizer#2065]
![20240506 ho download error](https://github.com/ho-dev/HattrickOrganizer/assets/66476803/bc57b840-25a1-4a61-9d61-c5659dc5a245)
**Describe the bug**
import of youth games breaks when a friendly youth game ran into shootoot, I think
[error importing youth friendly with penalty shootout wore than 22 shooters.txt](https://github.com/ho-dev/HattrickOrganizer/files/15222520/error.importing.youth.friendly.with.penalty.shootout.wore.than.22.shooters.txt)
![20240506 ho download](https://github.com/ho-dev/HattrickOrganizer/assets/66476803/a7a5aae5-a63e-4cfe-bd17-f4a3995eda8d)
![20240506 ho jugies](https://github.com/ho-dev/HattrickOrganizer/assets/66476803/a713d770-3579-4019-bfa9-6426b7206673)

**To Reproduce**
see attached report or ask angie, if it is possible to create imidiatly a game with penalty shootout with more than 20 shooters

**Screenshots**
attached 

**Platform information:**
windows10 22H2 Build 19045.4291 and before
HO version 8.0 (r613)
on JAVA Eclipse Temurin 17.0.6

**Additional context**

**Comment by wsbrenk** [comment]
In V8.0 i will try to truncate the match report length to the maximum column length of the current database version.

In V9 i will make the match report column length longer than 20000 characters.
