### ISSUE TITLE
[BUG] List of youth players does not get populated correct

### ISSUE THREAD

**Issue by hvbun** [ho-dev/HattrickOrganizer#2097]
**Describe the bug**
When opening the youth tab, the list of players does not get populated correctly
Clicking on an empty line, will still show match details.

**To Reproduce**
1. Go to the youth tab
2. See error

**Screenshots**
![image](https://github.com/ho-dev/HattrickOrganizer/assets/174112657/69cfa0eb-b59b-44ec-b67d-2ad3021c559d)

**Platform information:**
 - OS: [**Windows** / macOS / Linux]
 - Version 10 22H2 19045.4529

**WORK ARROUND**
Close the tab and open it again.
![image](https://github.com/ho-dev/HattrickOrganizer/assets/174112657/4a54bde3-f7c0-45d3-b97c-259c93142bda)

**Comment by wsbrenk** [comment]
if you can reproduce this error, please check the log file (in %APPDATA%/HO/logs) for error messages.
PLease upload these messages to this thread.

**Comment by hvbun** [comment]
[HO-1719851482.log](https://github.com/user-attachments/files/16056560/HO-1719851482.log)

**Comment by wsbrenk** [comment]
Thanks!

**Comment by hvbun** [comment]
Running HO81 Beta, I still see the issue reported

![image](https://github.com/ho-dev/HattrickOrganizer/assets/174112657/95f2697f-9152-450c-8ca7-a60db62d1d09)

**Comment by hvbun** [comment]
Log file

[HO-1720162498.log](https://github.com/user-attachments/files/16106103/HO-1720162498.log)

**Comment by wsbrenk** [comment]
@hvbun thanks for reporting - there is a new beta. could you please test again? Hopefully the error is not again in another place but gone.

**Comment by hvbun** [comment]
it seems to load fine in 8.1 BETA r650
thanks
