### ISSUE TITLE
[BUG] Wrong tag on best/worst team option

### ISSUE THREAD

**Issue by shagymt** [ho-dev/HattrickOrganizer#2139]
**Describe the bug**
"Peor equipo de la semana" is used twice, maybe the last one must be "Peor equipo de la **temporada**"

**To Reproduce**
1. Go to 'Funciones -> Mejor/Peor Equipo '

**Screenshots**
![image](https://github.com/user-attachments/assets/ba50504c-673a-4b03-a320-0239444761c1)

**Platform information:**
 - OS: Windows
 - Version 8.0

**Additional context**
Example of image

**Comment by sgcr** [comment]
Hi :)

I think you are right.
The text is two times in the translations for `bestOfWeek` and `worstOfWeek`.
I will try to change it in the POEDITOR project for Spanish.

Best regards
Sebastian
