### ISSUE TITLE
[FEATURE] Arena sizer: Add the general information about the current stadium

### ISSUE THREAD

**Issue by sgcr** [ho-dev/HattrickOrganizer#2140]
**Is your feature request related to a problem? Please describe.**
As a new contributor for HO I was looking for a small side project.
I saw the "Arena sizer" within the "Tools" and was missing the general information about the current stadium.
When clicking the UI, I recognized that clicking on the name of my stadium shows the same content when clicking on "Arena".
**So it might be a good idea to show in the tab with the stadium name the details about my stadium.**

**Describe the solution you'd like**
Please look at the screenshot to have an impression for the proposal.
3 group boxes from left to right containing the current, expansion and future of your stadium.
Each group box contains 3 columns: place type, places and the rate (or change) in percent.
the number of terraces, basic seating, seats under roof, seats in VIP boxes and and the total seats.
In the last line there is space for group box specific information.

The left group box **"Current"** shall show the normal information and of the stadium and in the last line is shown when the stadium was last improved or if there is a construction in progress.

The middle group box **"Expansion"** shall show the expansion of seats if there is any.
The number in the "Places" column should be with positive or negative sign in the specific color for that.
The percentage in third column "Change in %" shall show change in percent of each category (compared to the current places). The number in percent shall be shown with positive or negative sign in the specific color for that.
The last line shows when the current expansion is completed and an additional label with the remaining duration that is updated each second.

The last group box **"Future"** shall show the future of the stadium if there is an expansion in progress.
The future is the sum of current and expansion places for each type. The rate in percent shows how the rate of your stadium looks like after the expansion.
The last line shows the day when the future is reality (the next after completion).

**Proposal**
![Proposal_AreaInfoPanel](https://github.com/user-attachments/assets/92840f85-faac-463b-b6a0-2542dc4aebb9)

**Comment by tychobrailleur** [comment]
Nice!  And welcome!  I like the proposal, and great contribution (in particular the tests!!).  I have added some comments to the review.
