### ISSUE TITLE
[BUG] "Modules -> TeamAnalyzer -> Download a match" fails

### ISSUE THREAD

**Issue by skd** [ho-dev/HattrickOrganizer#2152]
"Modules -> TeamAnalyzer -> Download a match" fails. It brings into a state, where HO status bar says "Please wait ...", the progress bar is somewhat filled and still "loading", but the import dialog says " Import Failed.

(Ideally, HO should download friendly/cup opponent games via File->Download dialog.)

## To Reproduce
1. Modules -> TeamAnalyzer -> Download a match
2. Enter a valid Match-ID (open hattrick.org and navigate to the match, then from the URL copy the matchID URL parameter value)
3. Click Download
4. See "Import failed"

## Screenshots

![image](https://github.com/user-attachments/assets/93af2296-3783-40cc-b85a-d6b8fdb769e6)

## Platform information:
 - OS: Windows11
 - Version HO-8.1.655.2-portable-win-JRE

**Comment by wsbrenk** [comment]
The downloaded match is a cup match. Error is that downloader stores it as League match as selected by the download panel, whereas the match details correctly stores the cup type. Reloading match details fails because of this type mismatch.
