### ISSUE TITLE
[BUG] Player Analysis/PlayerCompare

### ISSUE THREAD

**Issue by TheBishop75** [ho-dev/HattrickOrganizer#2173]
No change in Best Position in the percentage, no matter what You choose in i.e, Playmaking or Form.

I am usin Windows 10 Pro, 22H2, 19045.5011

**Comment by wsbrenk** [comment]
Same as #2153 ?

**Comment by TheBishop75** [comment]
Yes

man. 4. nov. 2024 18.08 skrev wsbrenk ***@***.***>:
