### ISSUE TITLE
[BUG] Spanish translation not aplicable

### ISSUE THREAD

**Issue by jmbr4** [ho-dev/HattrickOrganizer#2215]
**Describe the bug**
Hi, 
I see that the last spanish translations added by Tavaro is not seeing in the app, in the release notes appears that are incluyed

**Screenshots**
Example:
![image](https://github.com/user-attachments/assets/78493621-332a-4773-b805-f3ad64b78055)

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version 9 r.975

**Comment by wsbrenk** [comment]
build log file contains this:


> Task :HattrickOrganizer:poeditorPull
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}
URL file: {"response":{"status":"fail","code":"403","message":"You don't have permission to access this resource"}}

**Comment by wsbrenk** [comment]
@tychobrailleur is this because you are not or no longer poeditor user in the ho translation project. i didn't find you if i wanted to add your account to the list of administrators.

**Comment by wsbrenk** [comment]
Resetted github secret

**Comment by tychobrailleur** [comment]
> @tychobrailleur is this because you are not or no longer poeditor user in the ho translation project. i didn't find you if i wanted to add your account to the list of administrators.

Odd, I definitely used to be part of the HO project on poeditor, not sure what happened there.

**Comment by jmbr4** [comment]
I see correctly with the last update :)

Same example:
![image](https://github.com/user-attachments/assets/5e6d4cd9-2df4-44a4-8d66-5306d3851aed)
