### ISSUE TITLE
[BUG] Error opening Arena Sizer

### ISSUE THREAD

**Issue by jmbr4** [ho-dev/HattrickOrganizer#2219]
Hi,

I'm updating my stadium, this morning (whit the r.725) i can open the arena size module, after I start the upgrade and this night I try to open arena sizer (whit r.727) an appears an error.

I don't know if the problem is the update or the arena sizer when you are upgrading a stadium.

![image](https://github.com/user-attachments/assets/f7f29e92-c86d-4c66-94c2-70830ef3e35f)

The logs don't show  more info, only the stacktrace.

**Comment by tychobrailleur** [comment]
I think it's the update, it doesn't seem to cater for the case where one of the seating type is 0 ([here](https://www85.hattrick.org/Club/Stadium/?stadiumId=2196288) VIP boxes)
