### ISSUE TITLE
[eFEAT] Insert foxtrick "psicotsi" data

### ISSUE THREAD

**Issue by mistermax80** [ho-dev/HattrickOrganizer#235]
I like to insert the psicotsi function in HO.
Foxtrick has this function, and It will be nice to have in HO.
@akasolace do you think we can consider this?

**Comment by akasolace** [comment]
Definitely, that’s a very good idea for next version.
1) We would need to use the server to get data. And then do some analysis. Can server cope with that ?
2) decide how to integrate that additional information

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mistermax80** [comment]
Yes of course!
But I don't understand what server should to do.
Could you explain better, how would you do?

**Comment by akasolace** [comment]
@mistermax80  I mean than in order to derive the TSI formula, we would need data. Players information from HO users could be send and store to the server. Once on the server we could do the required analysis.

**Comment by mistermax80** [comment]
Ok, so Di you want rewrite the formula?
Firstly, I would like to start from unwritten manual: TSI = (1.03*Difesa^3 + 1.03*Regia^3 + 1.03*Attacco^3 + 1.0*Passaggi^3 + 0.84*Cross^3)^2 * Calci^0.5 * Forma^0.5 / 1000

TSI_portiere = 3 * Parate^3.36 * Forma^0.5

Or we can see the code in foxtrick.

What do you think?

Anyway, the server can be do that work!

**Comment by yaute74** [comment]
In the same way it could be good to add some tools, like on HTLiveSight

**Comment by akasolace** [comment]
@mistermax80 I don't think we can use the formula from unwritten manual (e.g. age and status are not even mentionned)

**Comment by mistermax80** [comment]
@akasolace ok, you say right... and if we use the foxtrick code?

**Comment by akasolace** [comment]
@mistermax80  I see 4 options:

1. we ask user Chechesa  if we can use his formula:  https://hattrick.chechesa.com/en
2. we use formula from unwritten manual but only for player which are neither injured or above 28 yo
3. we use foxtrick formula if we can find them (it might be same formula as 2)
4. we derive our own formula

4. could be a nice long term solution  whereas we can start with 1, 2 or 3
I believe 1) to give fairly good result but no idea if Chechesa  will be willing to share, I am not even sure if he still playing hattrick

@DavidatorusF considering you know almost every HT player :-),  would you feel comfortable contacting Chechesa and asking him?

**Comment by mistermax80** [comment]
I like 5 :D sound good!!!!

**Comment by DavidatorusF** [comment]
on HTLS, we have ask to Tasos (HT-Tools creator) to use his tools... even if they are open source

about Psicotsi..nice tool for monoskill player... but now we have multiskill player

subskill seem to be better...
https://github.com/ventouris/hattricktools/blob/master/static/js/subskill.js

**Comment by akasolace** [comment]
@DavidatorusF  I looked at **subskill** and it does not look that good.
It is true that this kind of analysis is not that good with multiskill player but it is still better than nothing :-)

**Comment by akasolace** [comment]
As @mistermax80 suggested we will simply start to collect player's TSI as part of the existing feedback plugin. Hence we will start accumulating data as soon as 2.0 is release

**Comment by wsbrenk** [comment]
New Idea: Add "this" feature to the subskill adjustment dialog by adding current and calculated TSI to this dialog.
By adjusting the subs the user is able to narrow the both tsi numbers.

**Comment by wsbrenk** [comment]
TSI = (1.03*Def^3 + 1.03*PM^3 + 1.03*Sc^3 + 1.0*Ps^3 + 0.84*Wg^3)^2 * St^0.5 * Fm^0.5 / 1000

TSIgk = 3 * Gk^3.359 * Fm^0.5

(With Solid=6) (Note: non-existent stands for 0, disastrous starts at 0,01 and goes to 1. And so on, making solid 6,01-7,00, and not like generally accepted from 7 to 7,99)

**Comment by wsbrenk** [comment]
![image](https://github.com/ho-dev/HattrickOrganizer/assets/11821502/b11235f2-8bed-463f-adc8-a7dfd9d31538)
