### ISSUE TITLE
[eFEAT] Download right mother teen in transfer

### ISSUE THREAD

**Issue by mistermax80** [ho-dev/HattrickOrganizer#245]
I don't know if the cchp make available this information, but it will be nice to have the money income from old transfer! In particular it is interesting for young transfer.

**Comment by akasolace** [comment]
@mistermax80  do you mean transfer history of a given player ?

**Comment by mistermax80** [comment]
I'm refert to this income:
![image](https://user-images.githubusercontent.com/15519907/66382022-b3b9d500-e9ba-11e9-8424-40acc50647e2.png)

**Comment by akasolace** [comment]
@mistermax80 ah ok, I don't know. We can check in API documentation. If it is not available we can also open a ticket. You would only use it in economy tab or do you have something else in mind ?

**Comment by mistermax80** [comment]
I have not idea... we can choose what we can do... But I like to know for each player sold, which are the income gained. This can be useful for analysis on sells.

**Comment by wsbrenk** [comment]
Economy displays this: IncomeSoldPlayersCommission
IF this value is greater than 0, the transfer history of sold players could be downloaded to update their lists.

**Comment by wsbrenk** [comment]
commision is calculated from transfer prices an displayed in player's transfer history

**Comment by wsbrenk** [comment]
TODO:
Fired (deleted) player's transfers set playerId=0
* set the correct (old) playerid in transfer and update db
* tag players as deleted if their transfers shows playerid=0 and don't updated their transfer history anymore
