### ISSUE TITLE
[BUG] move feedback plugin to anvil server

### ISSUE THREAD

**Issue by akasolace** [ho-dev/HattrickOrganizer#583]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

**Comment by mistermax80** [comment]
@akasolace How are you, why do you want move the server towards anvil server? In php I made all.

Bye Bye

**Comment by akasolace** [comment]
Thing is I really don't know anything about PHP and the framework you used. 
I received some errors message on the server and I was completely stuck.
Also as I was not sure how much you would remain involve with the project ....
