### ISSUE TITLE
[FEATURE] determine gate opening for promotion/demotion on the server side

### ISSUE THREAD

**Issue by akasolace** [ho-dev/HattrickOrganizer#671]
HO should allow sending data for promotion/demotion on the Tuesday following the last match of the season. I am not sure how this is implemented. Maybe going forward, we could automtize this on the server side:
     - Tuesday at midnight: automatic reset of database, and allowing data push
     - HO would then not determine by itself if data can be putched it would fetch information from the server or maybe a mix of both (like if match day = 14 check on server otherwise return false)
      - the message on the website would also be automatized

**Comment by akasolace** [comment]
- in HO!: replace isActive() by fetching the information from the server (https://github.com/akasolace/HO/blob/b006955587a154feddecce687e5bb55cec0a0376/src/main/java/module/series/promotion/LeaguePromotionHandler.java#L50) 

`supportedLeagues`  => I think now all leagues are supported, we may remove this ----

  - on the server: 
     - create the endpoint that return isactivestatus ....

**Comment by akasolace** [comment]
I think HTCalendar.java and HTCalendarFactory.java are not correctly implemented but touching that low-level part of the code might have some bad side effect

**Comment by wsbrenk** [comment]
HOServer is disabled
