### ISSUE TITLE
changes in AutoLinueup checkboxes should (if possible) not be made via mouseListener

### ISSUE THREAD

**Issue by akasolace** [ho-dev/HattrickOrganizer#752]
see #744

maybe add something in ListSelectionListener of LineupPanel, or see how to cascade tableEvent rom sorter to model in AsutellungSpielerTable

from @weisJ 
> Also it like TableSorter is a custom table model for HO. So if sorting events aren’t propagated then there needs to be changes made to TableSorter itself.

**Comment by tychobrailleur** [comment]
I am not sure I understand what is needed here.  Is this still relevant?

**Comment by akasolace** [comment]
Yes it is still relevant but really not something urgent as it is working well as it is. I opened this ticket if someday there is really nothing else to do in HO! :-)
